# Generated by Django 2.1.3 on 2019-04-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpOwnData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_email', models.CharField(max_length=50)),
                ('owner_password', models.CharField(max_length=50)),
                ('owner_contact', models.CharField(max_length=50)),
            ],
        ),
    ]
