# Generated by Django 2.1.3 on 2019-04-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190422_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='PgDetailData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(max_length=50)),
                ('owner_contact', models.CharField(max_length=50)),
                ('pg_location', models.CharField(max_length=50)),
                ('pg_rent', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pgtable',
            },
        ),
    ]
