# Generated by Django 2.1.3 on 2019-04-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pgdetaildata'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgdetaildata',
            name='pic',
            field=models.FileField(default='media/defaultpic.png', upload_to='media/'),
        ),
    ]
