# Generated by Django 2.1.3 on 2019-04-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_pgdetaildata_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgdetaildata',
            name='pic',
            field=models.ImageField(default='media/defaultpic.png', upload_to='media/'),
        ),
    ]
