# Generated by Django 2.1.3 on 2019-04-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190425_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgdetaildata',
            name='pic',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
