# Generated by Django 2.1.3 on 2019-04-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190425_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgdetaildata',
            name='pic',
            field=models.FileField(default='media/defaultpic.png', upload_to='documents/'),
        ),
    ]
